#!/usr/bin/env node
// Generate src/content.ts from the markdown files in content/.
// Run this after editing the canonical artifacts in Dashboard/Artifacts/Security/.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const skillPath = join(root, "content", "SKILL_ai_integration_lead.md");
const checklistPath = join(root, "content", "AI_SECURITY_CHECKLIST.md");
const outPath = join(root, "src", "content.ts");

for (const p of [skillPath, checklistPath]) {
  if (!existsSync(p)) {
    console.error(`Missing ${p}`);
    process.exit(1);
  }
}

const skill = readFileSync(skillPath, "utf8");
const checklist = readFileSync(checklistPath, "utf8");

// Encode as a JSON string so backticks/${} in the markdown can't break the output.
const out = `// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand.
// Source files: content/SKILL_ai_integration_lead.md, content/AI_SECURITY_CHECKLIST.md.
// Run \`npm run sync-content\` after editing those.

export const SKILL_TEXT: string = ${JSON.stringify(skill)};

export const CHECKLIST_TEXT: string = ${JSON.stringify(checklist)};
`;

writeFileSync(outPath, out, "utf8");
console.log(
  `Wrote ${outPath} (${skill.length} + ${checklist.length} chars).`
);
